# For more info on HTTP files go to https://aka.ms/vs/httpfile
@OrderManagementSystem_HostAddress = http://localhost:5203

### Add Order
POST {{OrderManagementSystem_HostAddress}}/api/Order/Add
Content-Type: application/json

{
  "id": "O005",
  "productId": "P001",
  "cost": 500.5,
  "placed": "2022-01-05T00:00:00",
  "customerId": "C001",
  "status": "Process"
}

### Get All Orders
GET {{OrderManagementSystem_HostAddress}}/api/Order/GetAllOrders

### Get By ID
GET {{OrderManagementSystem_HostAddress}}/api/Order/GetById/O005

### Get By Customer ID
GET {{OrderManagementSystem_HostAddress}}/api/Order/GetByCustomerId/C001

### Cancel Order
DELETE {{OrderManagementSystem_HostAddress}}/api/Order/Cancel/O005
