SELECT DB_NAME();
use TOPBRAINS
CREATE TABLE ZIPCODE_INFO(
    ZIP_CODE VARCHAR(5),
    CITY     VARCHAR(10)
);
GO

CREATE TABLE INSTRUCTOR_INFO(
    INSTRUCTOR_ID        NUMERIC(8,0),
    INSTRUCTOR_FIRST_NAME VARCHAR(15),
    INSTRUCTOR_LAST_NAME  VARCHAR(15)
);
GO

CREATE TABLE COURSE_INFO(
    COURSE_NO NUMERIC(8,0),
    COST      NUMERIC(5,2)
);
GO

CREATE TABLE STUDENT_INFO(
    STUDENT_ID         NUMERIC(8,0),
    STUDENT_FIRST_NAME VARCHAR(15),
    STUDENT_LAST_NAME  VARCHAR(15)
);
GO

CREATE TABLE SECTION_INFO(
    SECTION_ID     NUMERIC(8,0),
    COURSE_NO      NUMERIC(8,0),
    SECTION_NO     NUMERIC(5),
    INSTRUCTOR_ID  NUMERIC(8,0)
);
GO

CREATE TABLE ENROLLMENT_INFO(
    STUDENT_ID NUMERIC(8,0),
    SECTION_ID NUMERIC(8,0)
);
GO

CREATE TABLE GRADE_INFO(
    STUDENT_ID           NUMERIC(8,0),
    SECTION_ID           NUMERIC(8,0),
    GRADE_TYPE_CODE      CHAR(2),
    GRADE_CODE_OCCURANCE NUMERIC(5)
);
GO
