USE TOPBRAINS;
ALTER TABLE ZIPCODE_INFO ALTER COLUMN ZIP_CODE VARCHAR(5) NOT NULL;
ALTER TABLE ZIPCODE_INFO ALTER COLUMN CITY VARCHAR(25) NOT NULL;
ALTER TABLE ZIPCODE_INFO ALTER COLUMN STATE VARCHAR(2) NOT NULL;
ALTER TABLE ZIPCODE_INFO ADD CONSTRAINT ZIP_PK PRIMARY KEY (ZIP_CODE);


ALTER TABLE INSTRUCTOR_INFO ALTER COLUMN INSTRUCTOR_ID NUMERIC(8,0) NOT NULL;
ALTER TABLE INSTRUCTOR_INFO ALTER COLUMN INSTRUCTOR_FIRST_NAME VARCHAR(25) NOT NULL;
ALTER TABLE INSTRUCTOR_INFO ALTER COLUMN INSTRUCTOR_LAST_NAME VARCHAR(25) NOT NULL;
ALTER TABLE INSTRUCTOR_INFO ADD CONSTRAINT INSTRUCTOR_ID_PK PRIMARY KEY (INSTRUCTOR_ID);
ALTER TABLE INSTRUCTOR_INFO ADD CONSTRAINT ZIP_INSTRUCTOR_FK FOREIGN KEY (ZIP_CODE) REFERENCES ZIPCODE_INFO(ZIP_CODE);


ALTER TABLE COURSE_INFO ALTER COLUMN COURSE_NO NUMERIC(8,0) NOT NULL;
ALTER TABLE COURSE_INFO ALTER COLUMN COURSE_NAME VARCHAR(50) NOT NULL;
ALTER TABLE COURSE_INFO ALTER COLUMN COST NUMERIC(9,2) NOT NULL;
ALTER TABLE COURSE_INFO ADD CONSTRAINT COURSE_NO_PK PRIMARY KEY (COURSE_NO);


ALTER TABLE STUDENT_INFO ALTER COLUMN STUDENT_ID NUMERIC(8,0) NOT NULL;
ALTER TABLE STUDENT_INFO ALTER COLUMN STUDENT_FIRST_NAME VARCHAR(25) NOT NULL;
ALTER TABLE STUDENT_INFO ALTER COLUMN STUDENT_LAST_NAME VARCHAR(25) NOT NULL;
ALTER TABLE STUDENT_INFO ADD CONSTRAINT STUDENT_ID_PK PRIMARY KEY (STUDENT_ID);
ALTER TABLE STUDENT_INFO ADD CONSTRAINT ZIP_STUDENT_FK FOREIGN KEY (ZIP_CODE) REFERENCES ZIPCODE_INFO(ZIP_CODE);


ALTER TABLE SECTION_INFO ALTER COLUMN SECTION_ID NUMERIC(8,0) NOT NULL;
ALTER TABLE SECTION_INFO ALTER COLUMN SECTION_NO NUMERIC(3,0) NOT NULL;
ALTER TABLE SECTION_INFO ADD CONSTRAINT SECTION_ID_PK PRIMARY KEY (SECTION_ID);
ALTER TABLE SECTION_INFO ADD CONSTRAINT COURSE_SECTION_FK FOREIGN KEY (COURSE_NO) REFERENCES COURSE_INFO(COURSE_NO);
ALTER TABLE SECTION_INFO ADD CONSTRAINT INSTRUCTOR_SECTION_FK FOREIGN KEY (INSTRUCTOR_ID) REFERENCES INSTRUCTOR_INFO(INSTRUCTOR_ID);


ALTER TABLE ENROLLMENT_INFO ALTER COLUMN STUDENT_ID NUMERIC(8,0) NOT NULL;
ALTER TABLE ENROLLMENT_INFO ALTER COLUMN SECTION_ID NUMERIC(8,0) NOT NULL;
ALTER TABLE ENROLLMENT_INFO ADD CONSTRAINT ENROLLMENT_STUD_SECT_PK PRIMARY KEY (STUDENT_ID, SECTION_ID);
ALTER TABLE ENROLLMENT_INFO ADD CONSTRAINT ENROLLMENT_STUDENT_ID_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID);
ALTER TABLE ENROLLMENT_INFO ADD CONSTRAINT ENROLLMENT_SECTION_ID_FK FOREIGN KEY (SECTION_ID) REFERENCES SECTION_INFO(SECTION_ID);


ALTER TABLE GRADE_INFO ALTER COLUMN STUDENT_ID NUMERIC(8,0) NOT NULL;
ALTER TABLE GRADE_INFO ALTER COLUMN SECTION_ID NUMERIC(8,0) NOT NULL;
ALTER TABLE GRADE_INFO ALTER COLUMN GRADE_TYPE_CODE CHAR(2) NOT NULL;
ALTER TABLE GRADE_INFO ALTER COLUMN GRADE_CODE_OCCURANCE NUMERIC(38,0) NOT NULL;
ALTER TABLE GRADE_INFO ALTER COLUMN NUMERIC_GRADE NUMERIC(3,0) NOT NULL;
ALTER TABLE GRADE_INFO ADD CONSTRAINT GRADE_STUD_SECT_TYPE_CODE_PK PRIMARY KEY (STUDENT_ID, SECTION_ID, GRADE_TYPE_CODE, GRADE_CODE_OCCURANCE);
ALTER TABLE GRADE_INFO ADD CONSTRAINT GRADE_STUDENT_ID_FK FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT_INFO(STUDENT_ID);
ALTER TABLE GRADE_INFO ADD CONSTRAINT GRADE_SECTION_ID_FK FOREIGN KEY (SECTION_ID) REFERENCES SECTION_INFO(SECTION_ID);
ALTER TABLE GRADE_INFO ADD CONSTRAINT CHK_GRADE_TYPE_CODE CHECK (GRADE_TYPE_CODE IN ('FI','HM','MT','PA','PJ','QZ'));
ALTER TABLE GRADE_INFO ADD CONSTRAINT NUMERIC_GRADE_DF DEFAULT 0 FOR NUMERIC_GRADE;

EXEC sp_help 'ZIPCODE_INFO';
EXEC sp_help 'GRADE_INFO';
--TO CHK IT