USE TOPBRAINS;
GO
CREATE TABLE EMPLOYEES
(
    ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    DEPT VARCHAR(30),
    SALARY INT
);
GO

INSERT INTO EMPLOYEES (ID, NAME, DEPT, SALARY) VALUES
(1, 'Amit',  'IT',    60000),
(2, 'Riya',  'IT',    75000),
(3, 'Karan', 'HR',    50000),
(4, 'Sneha', 'HR',    60000),
(5, 'Rahul', 'Sales', 45000),
(6, 'Neha',  'Sales', 70000);
GO


SELECT E.DEPT, E.NAME, E.SALARY
FROM EMPLOYEES E
JOIN
(
    SELECT DEPT, MAX(SALARY) AS MAX_SALARY
    FROM EMPLOYEES
    GROUP BY DEPT
) M
ON E.DEPT = M.DEPT
AND E.SALARY = M.MAX_SALARY;
