use TOPBRAINS;
GO

CREATE TABLE DEPARTMENT(
	DEPTID INT PRIMARY KEY,
	DEPTNAME VARCHAR(50)
);
GO

CREATE TABLE EMPLOYEES2(
	EMPID INT PRIMARY KEY,
	NAME VARCHAR(20),
	SALARY INT,
	DEPTID INT
);
GO


INSERT INTO DEPARTMENT (DEPTID, DEPTNAME) VALUES
(1, 'IT'),
(2, 'HR'),
(3, 'Finance'),
(4, 'Sales');
GO

INSERT INTO EMPLOYEES2 (EMPID, NAME, SALARY, DEPTID) VALUES
(1, 'Amit',   60000, 1),
(2, 'Riya',   90000, 1),
(3, 'Karan',  85000, 1),

(4, 'Sneha',  50000, 2),
(5, 'Rahul',  65000, 2),

(6, 'Neha',   72000, 3),
(7, 'Arjun',  88000, 3),

(8, 'Pooja',  40000, 4),
(9, 'Rohit',  60000, 4);
GO


SELECT * FROM EMPLOYEES2;
SELECT * FROM DEPARTMENT;

SELECT D.DEPTNAME, M.MAXSALARY AS HIGHEST_SALARY, E.NAME AS EMPLOYEENAME
FROM DEPARTMENT D 
JOIN 
(
	SELECT DEPTID, MAX(SALARY) AS MAXSALARY
	FROM EMPLOYEES2 
	GROUP BY DEPTID
	HAVING AVG(SALARY) > 70000
)M
ON D.DEPTID =M.DEPTID
JOIN EMPLOYEES2 E
ON E.DEPTID = M.DEPTID
AND E.SALARY = M.MAXSALARY;