USE TOPBRAINS;

CREATE TABLE ORDERS
(
    ORDER_ID INT PRIMARY KEY,
    ORDER_DATE DATE
);
GO

CREATE TABLE ORDERITEMS
(
    ORDER_ITEM_ID INT PRIMARY KEY,
    ORDER_ID INT,
    PRODUCT_NAME VARCHAR(50),
    QUANTITY INT
);
GO

INSERT INTO ORDERS (ORDER_ID, ORDER_DATE) VALUES (1001, '2024-01-01'), (1002, '2024-01-05');
GO

INSERT INTO ORDERITEMS VALUES (1,1001,'LAPTOP',1), (2,1002,'MOUSE',2), (3,1003,'KEYBOARD',1);
GO

SELECT * FROM ORDERITEMS;
SELECT * FROM ORDERS;

SELECT O1.* FROM ORDERITEMS O1
LEFT JOIN ORDERS O2
ON O1.ORDER_ID = O2.ORDER_ID
WHERE O2.ORDER_ID IS NULL;
GO



