USE TOPBRAINS;
GO

CREATE TABLE STUDENT
(
    STUDENT_ID INT PRIMARY KEY,
    STUDENT_NAME VARCHAR(50)
);
GO
CREATE TABLE MARKS
(
    MARK_ID INT IDENTITY(1,1) PRIMARY KEY,
    STUDENT_ID INT,
    MARKS INT,
    FOREIGN KEY (STUDENT_ID) REFERENCES STUDENT(STUDENT_ID)
);
GO

INSERT INTO STUDENT (STUDENT_ID, STUDENT_NAME) VALUES
(1, 'Amit'),
(2, 'Riya'),
(3, 'Karan'),
(4, 'Sneha');
GO

INSERT INTO MARKS (STUDENT_ID, MARKS) VALUES
(1, 85),
(2, 90);
GO

SELECT * FROM STUDENT;
SELECT * FROM MARKS;

DELETE S
FROM STUDENT S
LEFT JOIN MARKS M
ON S.STUDENT_ID = M.STUDENT_ID
WHERE M.STUDENT_ID IS NULL;
GO

SELECT * FROM STUDENT;

