USE TOPBRAINS;
GO

CREATE TABLE PRODUCTS
(
    PRODUCT_ID INT PRIMARY KEY,
    PRODUCT_NAME VARCHAR(50),
    PRICE DECIMAL(10,2)
);
GO

CREATE TABLE SALES
(
    SALE_ID INT IDENTITY(1,1) PRIMARY KEY,
    PRODUCT_ID INT,
    QUANTITY INT,
    SALE_DATE DATE,
    FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID)
);
GO

INSERT INTO PRODUCTS (PRODUCT_ID, PRODUCT_NAME, PRICE) VALUES
(1, 'Laptop', 60000),
(2, 'Mouse', 500),
(3, 'Keyboard', 1200),
(4, 'Monitor', 15000);
GO


INSERT INTO SALES (PRODUCT_ID, QUANTITY, SALE_DATE) VALUES
(1, 2, '2024-01-10'),
(2, 5, '2024-01-12'),
(4, 1, '2024-01-15');
GO


SELECT * FROM PRODUCTS;
SELECT * FROM SALES;

SELECT P.PRODUCT_ID, P.PRODUCT_NAME, P.PRICE
FROM PRODUCTS P
WHERE NOT EXISTS
(
    SELECT 1
    FROM SALES S
    WHERE S.PRODUCT_ID = P.PRODUCT_ID
);
